library(htmlwidgets)
library(shiny)
library(ggplot2)
library(DT)
library(plyr)
library(dplyr)
library(leaflet)
library(rlang)
library(BAMMtools)
library(grid)
library(gridExtra)
library(shinyjs)
library(highcharter)

colfunc = colorRampPalette(c("red","white","blue"))

mround <- function(x,base){ 
  base*round(x/base) 
}

dem_rep_choices = c("", "Trump 2016 Share", "Clinton 2016 Share")

NYT_url <- a("the New York Times", href="http://www.nytimes.com/elections/results/president")
Git_url <- a("Github here.", href="https://github.com/Deleetdk/USA.county.data")
Kaggle_url <- a("Kaggle here.", href="https://www.kaggle.com/benhamner/2016-us-election/data")
shape_url <- a("Census Bureau's MAF/TIGER geographic database.", href="https://www.census.gov/geo/maps-data/data/cbf/cbf_counties.html")

load("ScoreGeoData2.RData")

ui <- shinyUI(
  navbarPage("Predicting Trump Counties using Machine Learning",
             selected = "About",
             useShinyjs(),
             tabPanel("About",
                      sidebarLayout(
                        sidebarPanel(
                          h2("2016 General Election Data Exploration Tool"),
                          div("This tool utilizes publicly available data and a variety of R packages to allow the user to visualize the results of the 2016 General election in concert with a number of different data points.  Data points include various demographic county-level data points, a score indicating whether or not Trump won a county, and the actual election results from the 2016 election.", style = "font-size:130%"),
                          br(),
                          div("This tool can be easily adapted to fit almost any geography and dataset, giving the user a analytical platform to draw actionable conclusions.", style = "font-size:130%")
                        ),
                        mainPanel(
                          h2("Methodology"),
                          div("A 2016 General election Trump county model was developed using county-level demographic data.", style = "font-size:130%"),
                          br(),
                          div("- The county data was passed through machine learning algorithms to develop the final model.", style = "font-size:120%"),
                          br(),
                          div("- A predictive score was then applied to each county in the US.", style = "font-size:120%"),
                          br(),
                          div("- A score of 0 represents a 0% chance that Trump won that county in the 2016 General election; a score of 100 represents a 100% chance.", style = "font-size:120%"),
                          br(),
                          h3("Plotting data"),
                          div("- Election results: County-level election results for the 2016 General election was pulled from ", tagList(NYT_url)," and can be found on ", tagList(Git_url), style = "font-size:120%"),
                          br(),
                          div("- Demographic data: County-level demographic data containing a number of different dataponts from the US Census Bureau can be found on ",tagList(Kaggle_url), style = "font-size:120%"),
                          h3("Geographic data"),
                          div("- Catographic Boundary Shapefiles: County-level shapefiles for the entire US were pulled from the ", tagList(shape_url),style = "font-size:120%"),
                          br()
                        )
                      )
             ),
             tabPanel("Mapping",
                      div(class="outer",
                          tags$head(
                            # Include our custom CSS
                            includeCSS("styles.css")),
                          # Output the map generated by leaflet
                          leafletOutput("map1", width = "100%", height = "100%"),
                          uiOutput("factors")
                      )
             )))
server <- shinyServer(function(input, output, session)  {
  runjs("Shiny.onInputChange('screen_width',window.screen.width);")
  runjs("Shiny.onInputChange('screen_height', window.screen.height);")
  emc_datatable <- function(data_to_show, rows = 5){
    datatable(data_to_show,
              options = list(
                columnDefs = list(list(className = 'dt-center', targets = 2)),
                pageLength = rows,
                lengthMenu = seq(rows,rows),
                # This JS function will give identifying county/row information
                # to a global variable in R (t2). Row data is accessed through
                # the JS variable this.api().rows(<index>).data()
                rowCallback = JS(
                  "function(settings, json) {",
                  "var tbl = this.api();",
                  "$(this.api().rows().nodes()).on({
                  mouseenter: function () {
                  var idx = this._DT_RowIndex;
                  Shiny.onInputChange('t2', tbl.rows(idx).data());
                  },
                  mouseleave: function () {
                  Shiny.onInputChange('t2', 'NULL');
                  }
  });",
                "}")))
    }
  
  emc_polygons <- function(map, data, pal, labs, func = T){
    if(func){
      addPolygons(map = map, data=merged2,
                  layerId = merged2@data$CountyState,
                  label = labs,
                  labelOptions = labelOptions(
                    style = list("font-weight" = "normal", padding = "3px 8px"),
                    textsize = "15px",
                    direction = "auto"),
                  fillColor = ~pal(data),
                  weight = 1,
                  opacity = 1,
                  color = I("grey"),
                  fillOpacity = 1,
                  highlight = highlightOptions(
                    weight = 5,
                    color = "#666",
                    dashArray = "",
                    fillOpacity = 0.7,
                    bringToFront = TRUE),
                  group = "polygons")
    } else {
      addPolygons(map = map, data=merged2,
                  layerId = merged2@data$CountyState,
                  label = labs,
                  labelOptions = labelOptions(
                    style = list("font-weight" = "normal", padding = "3px 8px"),
                    textsize = "15px",
                    direction = "auto"),
                  fillColor = pal,
                  weight = 1,
                  opacity = 1,
                  color = I("grey"),
                  fillOpacity = 1,
                  highlight = highlightOptions(
                    weight = 5,
                    color = "#666",
                    dashArray = "",
                    fillOpacity = 0.7,
                    bringToFront = TRUE),
                  group = "polygons")
    }
  }
  
  
  output$factors <- renderUI({
    absolutePanel(id = "controls", class = "panel panel-default", fixed = TRUE,
                  draggable = TRUE, top = 60, left = "auto", right = 10, bottom = "auto",
                  width = "650px", height = "520px",
                  tabsetPanel(
                    tabPanel("Factors",
                             br(),
                             selectInput("var1",
                                         label = "Choose a factor to map:",
                                         choices = c("Trump County score","Trump 2016 Share","Clinton 2016 Share","Population, 2014 estimate","Population, 2010 (April 1) estimates base","Population, percent change - April 1, 2010 to July 1, 2014",
                                                     "Population, 2010","Persons under 5 years, percent, 2014","Persons under 18 years, percent, 2014","Persons 65 years and over, percent, 2014",
                                                     "Female persons, percent, 2014","White alone, percent, 2014","Black or African American alone, percent, 2014",
                                                     "American Indian and Alaska Native alone, percent, 2014","Asian alone, percent, 2014","Native Hawaiian and Other Pacific Islander alone, percent, 2014",
                                                     "Two or More Races, percent, 2014","Hispanic or Latino, percent, 2014","White alone, not Hispanic or Latino, percent, 2014",
                                                     "Living in same house 1 year & over, percent, 2009-2013","Foreign born persons, percent, 2009-2013",
                                                     "Language other than English spoken at home, pct age 5+, 2009-2013","High school graduate or higher, percent of persons age 25+, 2009-2013",
                                                     "Bachelor's degree or higher, percent of persons age 25+, 2009-2013","Veterans, 2009-2013","Mean travel time to work (minutes), workers age 16+, 2009-2013",
                                                     "Housing units, 2014","Homeownership rate, 2009-2013","Housing units in multi-unit structures, percent, 2009-2013",
                                                     "Median value of owner-occupied housing units, 2009-2013","Households, 2009-2013","Persons per household, 2009-2013",
                                                     "Per capita money income in past 12 months (2013 dollars), 2009-2013","Median household income, 2009-2013",
                                                     "Persons below poverty level, percent, 2009-2013","Private nonfarm establishments, 2013","Private nonfarm employment,  2013",
                                                     "Private nonfarm employment, percent change, 2012-2013","Nonemployer establishments, 2013","Total number of firms, 2007",
                                                     "Black-owned firms, percent, 2007","American Indian- and Alaska Native-owned firms, percent, 2007","Asian-owned firms, percent, 2007",
                                                     "Native Hawaiian- and Other Pacific Islander-owned firms, percent, 2007","Hispanic-owned firms, percent, 2007","Women-owned firms, percent, 2007",
                                                     "Manufacturers shipments, 2007 ($1,000)","Merchant wholesaler sales, 2007 ($1,000)","Retail sales, 2007 ($1,000)","Retail sales per capita, 2007",
                                                     "Accommodation and food services sales, 2007 ($1,000)","Building permits, 2014","Land area in square miles, 2010","Population per square mile, 2010")),
                             div(dataTableOutput("selectedFactor"), style = "font-size: 100%; width: 100%; height: 90%;", fillContainer=T)),
                    tabPanel("Differentials",
                             br(),
                             column(12, align="center",
                                    div(style = "display: inline-block;vertical-align:top; width: 48%;",
                                        selectInput("d1",
                                                    label = "First differential:",
                                                    choices = dem_rep_choices)),
                                    div(style = "display: inline-block;vertical-align:top; width: 48%;",
                                        selectInput("d2",
                                                    label = "Second differential:",
                                                    choices = dem_rep_choices)),
                                    actionButton("go", "Differentiate", width = "100%"),
                                    hr(),
                                    helpText(
                                      h4("Differential calculated as follows:"),
                                      h5(tags$i(paste0("Differential = First - Second")))))
                    )))
  })
  
  
  observeEvent(input$d1, {
    if(input$d1 != ""){
      updateSelectInput(session, "d2",
                        label = "Second differential:",
                        choices = dem_rep_choices[! dem_rep_choices %in% input$d1],
                        selected = NULL)
    }
  })
  
  
  
  # Initialize reactive dataframe elements. This 'dataframe' will send an update to any function using
  # its values whenever one of the values is changed by user input
  reactive <- reactiveValues(dataSel = merged2@data$TrumpCountiesScore, 
                             titleSel = "Trump County Score", 
                             textSel = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Trump Counties Score: ",round(TrumpCountiesScore, digits=2))),
                             subSel = "Trump County Score",
                             colorSel = "RdPu",
                             binSel = 6,
                             digitSel = 2,
                             percenSel = 0)
  
  # Observe event for data, title, type, and text selection
  observeEvent(input$var1, {
    # What data has been chosen by the user based on 'factor' input?
    reactive$dataSel = switch(input$var1,
                              "Trump County score" = merged2@data$TrumpCountiesScore,
                              "Trump 2016 Share" = merged2@data$TrumpShare,
                              "Clinton 2016 Share" = merged2@data$ClintonShare,
                              "Population, 2014 estimate" = merged2@data$PST045214,
                              "Population, 2010 (April 1) estimates base" = merged2@data$PST040210,
                              "Population, percent change - April 1, 2010 to July 1, 2014" = merged2@data$PST120214,
                              "Population, 2010" = merged2@data$POP010210,
                              "Persons under 5 years, percent, 2014" = merged2@data$AGE135214,
                              "Persons under 18 years, percent, 2014" = merged2@data$AGE295214,
                              "Persons 65 years and over, percent, 2014" = merged2@data$AGE775214,
                              "Female persons, percent, 2014" = merged2@data$SEX255214,
                              "White alone, percent, 2014" = merged2@data$RHI125214,
                              "Black or African American alone, percent, 2014" = merged2@data$RHI225214,
                              "American Indian and Alaska Native alone, percent, 2014" = merged2@data$RHI325214,
                              "Asian alone, percent, 2014" = merged2@data$RHI425214,
                              "Native Hawaiian and Other Pacific Islander alone, percent, 2014" = merged2@data$RHI525214,
                              "Two or More Races, percent, 2014" = merged2@data$RHI625214,
                              "Hispanic or Latino, percent, 2014" = merged2@data$RHI725214,
                              "White alone, not Hispanic or Latino, percent, 2014" = merged2@data$RHI825214,
                              "Living in same house 1 year & over, percent, 2009-2013" = merged2@data$POP715213,
                              "Foreign born persons, percent, 2009-2013" = merged2@data$POP645213,
                              "Language other than English spoken at home, pct age 5+, 2009-2013" = merged2@data$POP815213,
                              "High school graduate or higher, percent of persons age 25+, 2009-2013" = merged2@data$EDU635213,
                              "Bachelor's degree or higher, percent of persons age 25+, 2009-2013" = merged2@data$EDU685213,
                              "Veterans, 2009-2013" = merged2@data$VET605213,
                              "Mean travel time to work (minutes), workers age 16+, 2009-2013" = merged2@data$LFE305213,
                              "Housing units, 2014" = merged2@data$HSG010214,
                              "Homeownership rate, 2009-2013" = merged2@data$HSG445213,
                              "Housing units in multi-unit structures, percent, 2009-2013" = merged2@data$HSG096213,
                              "Median value of owner-occupied housing units, 2009-2013" = merged2@data$HSG495213,
                              "Households, 2009-2013" = merged2@data$HSD410213,
                              "Persons per household, 2009-2013" = merged2@data$HSD310213,
                              "Per capita money income in past 12 months (2013 dollars), 2009-2013" = merged2@data$INC910213,
                              "Median household income, 2009-2013" = merged2@data$INC110213,
                              "Persons below poverty level, percent, 2009-2013" = merged2@data$PVY020213,
                              "Private nonfarm establishments, 2013" = merged2@data$BZA010213,
                              "Private nonfarm employment,  2013" = merged2@data$BZA110213,
                              "Private nonfarm employment, percent change, 2012-2013" = merged2@data$BZA115213,
                              "Nonemployer establishments, 2013" = merged2@data$NES010213,
                              "Total number of firms, 2007" = merged2@data$SBO001207,
                              "Black-owned firms, percent, 2007" = merged2@data$SBO315207,
                              "American Indian- and Alaska Native-owned firms, percent, 2007" = merged2@data$SBO115207,
                              "Asian-owned firms, percent, 2007" = merged2@data$SBO215207,
                              "Native Hawaiian- and Other Pacific Islander-owned firms, percent, 2007" = merged2@data$SBO515207,
                              "Hispanic-owned firms, percent, 2007" = merged2@data$SBO415207,
                              "Women-owned firms, percent, 2007" = merged2@data$SBO015207,
                              "Manufacturers shipments, 2007 ($1,000)" = merged2@data$MAN450207,
                              "Merchant wholesaler sales, 2007 ($1,000)" = merged2@data$WTN220207,
                              "Retail sales, 2007 ($1,000)" = merged2@data$RTN130207,
                              "Retail sales per capita, 2007" = merged2@data$RTN131207,
                              "Accommodation and food services sales, 2007 ($1,000)" = merged2@data$AFN120207,
                              "Building permits, 2014" = merged2@data$BPS030214,
                              "Land area in square miles, 2010" = merged2@data$LND110210,
                              "Population per square mile, 2010" = merged2@data$POP060210)
    
    # What legend title should be displayed based on factor input?
    reactive$titleSel = switch(input$var1,
                               "Trump County score" = "Trump County score",
                               "Trump 2016 Share" = "Trump 2016 Share",
                               "Clinton 2016 Share" = "Clinton 2016 Share",
                               "Population, 2014 estimate" = "Population, 2014 estimate",
                               "Population, 2010 (April 1) estimates base" = "Population, 2010 (April 1) estimates base",
                               "Population, percent change - April 1, 2010 to July 1, 2014" = "Population, percent change - April 1, 2010 to July 1, 2014",
                               "Population, 2010" = "Population, 2010",
                               "Persons under 5 years, percent, 2014" = "Persons under 5 years, percent, 2014",
                               "Persons under 18 years, percent, 2014" = "Persons under 18 years, percent, 2014",
                               "Persons 65 years and over, percent, 2014" = "Persons 65 years and over, percent, 2014",
                               "Female persons, percent, 2014" = "Female persons, percent, 2014",
                               "White alone, percent, 2014" = "White alone, percent, 2014",
                               "Black or African American alone, percent, 2014" = "Black or African American alone, percent, 2014",
                               "American Indian and Alaska Native alone, percent, 2014" = "American Indian and Alaska Native alone, percent, 2014",
                               "Asian alone, percent, 2014" = "Asian alone, percent, 2014",
                               "Native Hawaiian and Other Pacific Islander alone, percent, 2014" = "Native Hawaiian and Other Pacific Islander alone, percent, 2014",
                               "Two or More Races, percent, 2014" = "Two or More Races, percent, 2014",
                               "Hispanic or Latino, percent, 2014" = "Hispanic or Latino, percent, 2014",
                               "White alone, not Hispanic or Latino, percent, 2014" = "White alone, not Hispanic or Latino, percent, 2014",
                               "Living in same house 1 year & over, percent, 2009-2013" = "Living in same house 1 year & over, percent, 2009-2013",
                               "Foreign born persons, percent, 2009-2013" = "Foreign born persons, percent, 2009-2013",
                               "Language other than English spoken at home, pct age 5+, 2009-2013" = "Language other than English spoken at home, pct age 5+, 2009-2013",
                               "High school graduate or higher, percent of persons age 25+, 2009-2013" = "High school graduate or higher, percent of persons age 25+, 2009-2013",
                               "Bachelor's degree or higher, percent of persons age 25+, 2009-2013" = "Bachelor's degree or higher, percent of persons age 25+, 2009-2013",
                               "Veterans, 2009-2013" = "Veterans, 2009-2013",
                               "Mean travel time to work (minutes), workers age 16+, 2009-2013" = "Mean travel time to work (minutes), workers age 16+, 2009-2013",
                               "Housing units, 2014" = "Housing units, 2014",
                               "Homeownership rate, 2009-2013" = "Homeownership rate, 2009-2013",
                               "Housing units in multi-unit structures, percent, 2009-2013" = "Housing units in multi-unit structures, percent, 2009-2013",
                               "Median value of owner-occupied housing units, 2009-2013" = "Median value of owner-occupied housing units, 2009-2013",
                               "Households, 2009-2013" = "Households, 2009-2013",
                               "Persons per household, 2009-2013" = "Persons per household, 2009-2013",
                               "Per capita money income in past 12 months (2013 dollars), 2009-2013" = "Per capita money income in past 12 months (2013 dollars), 2009-2013",
                               "Median household income, 2009-2013" = "Median household income, 2009-2013",
                               "Persons below poverty level, percent, 2009-2013" = "Persons below poverty level, percent, 2009-2013",
                               "Private nonfarm establishments, 2013" = "Private nonfarm establishments, 2013",
                               "Private nonfarm employment,  2013" = "Private nonfarm employment,  2013",
                               "Private nonfarm employment, percent change, 2012-2013" = "Private nonfarm employment, percent change, 2012-2013",
                               "Nonemployer establishments, 2013" = "Nonemployer establishments, 2013",
                               "Total number of firms, 2007" = "Total number of firms, 2007",
                               "Black-owned firms, percent, 2007" = "Black-owned firms, percent, 2007",
                               "American Indian- and Alaska Native-owned firms, percent, 2007" = "American Indian- and Alaska Native-owned firms, percent, 2007",
                               "Asian-owned firms, percent, 2007" = "Asian-owned firms, percent, 2007",
                               "Native Hawaiian- and Other Pacific Islander-owned firms, percent, 2007" = "Native Hawaiian- and Other Pacific Islander-owned firms, percent, 2007",
                               "Hispanic-owned firms, percent, 2007" = "Hispanic-owned firms, percent, 2007",
                               "Women-owned firms, percent, 2007" = "Women-owned firms, percent, 2007",
                               "Manufacturers shipments, 2007 ($1,000)" = "Manufacturers shipments, 2007 ($1,000)",
                               "Merchant wholesaler sales, 2007 ($1,000)" = "Merchant wholesaler sales, 2007 ($1,000)",
                               "Retail sales, 2007 ($1,000)" = "Retail sales, 2007 ($1,000)",
                               "Retail sales per capita, 2007" = "Retail sales per capita, 2007",
                               "Accommodation and food services sales, 2007 ($1,000)" = "Accommodation and food services sales, 2007 ($1,000)",
                               "Building permits, 2014" = "Building permits, 2014",
                               "Land area in square miles, 2010" = "Land area in square miles, 2010",
                               "Population per square mile, 2010" = "Population per square mile, 2010")
    
    # What information should hover boxes contain based on factor input?
    reactive$textSel = switch(input$var1,
                              "Trump County score" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Trump Counties Score: ",round(TrumpCountiesScore, digits=2))),
                              "Persons under 5 years, percent, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Persons under 5 years, percent, 2014: ",paste0(round(AGE135214, digits=2) ,"%%"))),
                              "Persons under 18 years, percent, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Persons under 18 years, percent, 2014: ", paste0(round(AGE295214, digits=2) ,"%%"))),
                              "Persons 65 years and over, percent, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Persons 65 years and over, percent, 2014: ", paste0(round(AGE775214, digits=2) ,"%%"))),
                              "Private nonfarm employment, percent change, 2012-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Private nonfarm employment, percent change, 2012-2013: ", paste0(round(BZA115213, digits=2) ,"%%"))),
                              "High school graduate or higher, percent of persons age 25+, 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"High school graduate or higher, percent of persons age 25+, 2009-2013: ", paste0(round(EDU635213, digits=2) ,"%%"))),
                              "Bachelor's degree or higher, percent of persons age 25+, 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Bachelor's degree or higher, percent of persons age 25+, 2009-2013: ", paste0(round(EDU685213, digits=2) ,"%%"))),
                              "Housing units in multi-unit structures, percent, 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Housing units in multi-unit structures, percent, 2009-2013: ", paste0(round(HSG096213, digits=2) ,"%%"))),
                              "Foreign born persons, percent, 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Foreign born persons, percent, 2009-2013: ", paste0(round(POP645213, digits=2) ,"%%"))),
                              "Living in same house 1 year & over, percent, 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Living in same house 1 year & over, percent, 2009-2013: ", paste0(round(POP715213, digits=2) ,"%%"))),
                              "Population, percent change - April 1, 2010 to July 1, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Population, percent change - April 1, 2010 to July 1, 2014: ", paste0(round(PST120214, digits=2) ,"%%"))),
                              "Persons below poverty level, percent, 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Persons below poverty level, percent, 2009-2013: ", paste0(round(PVY020213, digits=2) ,"%%"))),
                              "White alone, percent, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"White alone, percent, 2014: ", paste0(round(RHI125214, digits=2) ,"%%"))),
                              "Black or African American alone, percent, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Black or African American alone, percent, 2014: ", paste0(round(RHI225214, digits=2) ,"%%"))),
                              "American Indian and Alaska Native alone, percent, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"American Indian and Alaska Native alone, percent, 2014: ", paste0(round(RHI325214, digits=2) ,"%%"))),
                              "Asian alone, percent, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Asian alone, percent, 2014: ", paste0(round(RHI425214, digits=2) ,"%%"))),
                              "Native Hawaiian and Other Pacific Islander alone, percent, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Native Hawaiian and Other Pacific Islander alone, percent, 2014: ", paste0(round(RHI525214, digits=2) ,"%%"))),
                              "Two or More Races, percent, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Two or More Races, percent, 2014: ", paste0(round(RHI625214, digits=2) ,"%%"))),
                              "Hispanic or Latino, percent, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Hispanic or Latino, percent, 2014: ", paste0(round(RHI725214, digits=2) ,"%%"))),
                              "White alone, not Hispanic or Latino, percent, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"White alone, not Hispanic or Latino, percent, 2014: ", paste0(round(RHI825214, digits=2) ,"%%"))),
                              "Women-owned firms, percent, 2007" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Women-owned firms, percent, 2007: ", paste0(round(SBO015207, digits=2) ,"%%"))),
                              "American Indian- and Alaska Native-owned firms, percent, 2007" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"American Indian- and Alaska Native-owned firms, percent, 2007: ", paste0(round(SBO115207, digits=2) ,"%%"))),
                              "Asian-owned firms, percent, 2007" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Asian-owned firms, percent, 2007: ", paste0(round(SBO215207, digits=2) ,"%%"))),
                              "Black-owned firms, percent, 2007" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Black-owned firms, percent, 2007: ", paste0(round(SBO315207, digits=2) ,"%%"))),
                              "Hispanic-owned firms, percent, 2007" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Hispanic-owned firms, percent, 2007: ", paste0(round(SBO415207, digits=2) ,"%%"))),
                              "Native Hawaiian- and Other Pacific Islander-owned firms, percent, 2007" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Native Hawaiian- and Other Pacific Islander-owned firms, percent, 2007: ", paste0(round(SBO515207, digits=2) ,"%%"))),
                              "Female persons, percent, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Female persons, percent, 2014: ", paste0(round(SEX255214, digits=2) ,"%%"))),
                              "Trump 2016 Share" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Trump 2016 Share: ", paste0(round(TrumpShare, digits=2) ,"%%"))),
                              "Clinton 2016 Share" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Clinton 2016 Share: ", paste0(round(ClintonShare, digits=2),"%%"))),
                              "Population, 2014 estimate" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Population, 2014 estimate: ", format(PST045214, big.mark =",", trim=TRUE))),
                              "Population, 2010 (April 1) estimates base" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Population, 2010 (April 1) estimates base: ", format(PST040210, big.mark =",", trim=TRUE))),
                              "Population, 2010" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Population, 2010: ", format(POP010210, big.mark =",", trim=TRUE))),
                              "Language other than English spoken at home, pct age 5+, 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Language other than English spoken at home, pct age 5+, 2009-2013: ", paste0(round(POP815213, digits = 2), "%%"))),
                              "Veterans, 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Veterans, 2009-2013: ", format(VET605213, big.mark =",", trim=TRUE))),
                              "Mean travel time to work (minutes), workers age 16+, 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Mean travel time to work (minutes), workers age 16+, 2009-2013: ", round(LFE305213, digits = 2))),
                              "Housing units, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Housing units, 2014: ", format(HSG010214, big.mark =",", trim=TRUE))),
                              "Homeownership rate, 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Homeownership rate, 2009-2013: ", paste0(round(HSG445213, digits = 2), "%%"))),
                              "Median value of owner-occupied housing units, 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Median value of owner-occupied housing units, 2009-2013: ", paste0("$",format(HSG495213, big.mark =",", trim=TRUE)))),
                              "Households, 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Households, 2009-2013: ", format(HSD410213, big.mark =",", trim=TRUE))),
                              "Persons per household, 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Persons per household, 2009-2013: ", round(HSD310213, digits = 2))),
                              "Per capita money income in past 12 months (2013 dollars), 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Per capita money income in past 12 months (2013 dollars), 2009-2013: ", paste0("$",format(INC910213, big.mark =",", trim=TRUE)))),
                              "Median household income, 2009-2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Median household income, 2009-2013: ", paste0("$",format(INC110213, big.mark =",", trim=TRUE)))),
                              "Private nonfarm establishments, 2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Private nonfarm establishments, 2013: ", format(BZA010213, big.mark =",", trim=TRUE))),
                              "Private nonfarm employment,  2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Private nonfarm employment,  2013: ", format(BZA110213, big.mark =",", trim=TRUE))),
                              "Nonemployer establishments, 2013" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Nonemployer establishments, 2013: ", format(NES010213, big.mark =",", trim=TRUE))),
                              "Total number of firms, 2007" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Total number of firms, 2007: ", format(SBO001207, big.mark =",", trim=TRUE))),
                              "Manufacturers shipments, 2007 ($1,000)" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Manufacturers shipments, 2007 ($1,000): ", paste0("$",format(MAN450207, big.mark =",", trim=TRUE)))),
                              "Merchant wholesaler sales, 2007 ($1,000)" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Merchant wholesaler sales, 2007 ($1,000): ", paste0("$",format(WTN220207, big.mark =",", trim=TRUE)))),
                              "Retail sales, 2007 ($1,000)" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Retail sales, 2007 ($1,000): ", paste0("$",format(RTN130207, big.mark =",", trim=TRUE)))),
                              "Retail sales per capita, 2007" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Retail sales per capita, 2007: ", paste0("$",format(RTN131207, big.mark =",", trim=TRUE)))),
                              "Accommodation and food services sales, 2007 ($1,000)" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Accommodation and food services sales, 2007 ($1,000): ", paste0("$",format(AFN120207, big.mark =",", trim=TRUE)))),
                              "Building permits, 2014" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Building permits, 2014: ", format(BPS030214, big.mark =",", trim=TRUE))),
                              "Land area in square miles, 2010" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Land area in square miles, 2010: ", format(LND110210, big.mark =",", trim=TRUE))),
                              "Population per square mile, 2010" = with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Population per square mile, 2010: ", round(POP060210, digits = 2))))
    

    # What color should be mapped based on factor input?
    reactive$colorSel = switch(input$var1,
                               "Trump County score" = "RdPu",
                               "Trump 2016 Share" = "Reds",
                               "Clinton 2016 Share" = "Blues",
                               "Population, 2014 estimate" = "YlOrBr",
                               "Population, 2010 (April 1) estimates base" = "YlOrBr",
                               "Population, percent change - April 1, 2010 to July 1, 2014" = "YlOrBr",
                               "Population, 2010" = "YlOrBr",
                               "Persons under 5 years, percent, 2014" = "YlOrBr",
                               "Persons under 18 years, percent, 2014" = "YlOrBr",
                               "Persons 65 years and over, percent, 2014" = "YlOrBr",
                               "Female persons, percent, 2014" = "YlOrBr",
                               "White alone, percent, 2014" = "Purples",
                               "Black or African American alone, percent, 2014" = "Purples",
                               "American Indian and Alaska Native alone, percent, 2014" = "Purples",
                               "Asian alone, percent, 2014" = "Purples",
                               "Native Hawaiian and Other Pacific Islander alone, percent, 2014" = "Purples",
                               "Two or More Races, percent, 2014" = "Purples",
                               "Hispanic or Latino, percent, 2014" = "Purples",
                               "White alone, not Hispanic or Latino, percent, 2014" = "Purples",
                               "Living in same house 1 year & over, percent, 2009-2013" = "YlOrBr",
                               "Foreign born persons, percent, 2009-2013" = "YlOrBr",
                               "Language other than English spoken at home, pct age 5+, 2009-2013" = "YlOrBr",
                               "High school graduate or higher, percent of persons age 25+, 2009-2013" = "YlOrBr",
                               "Bachelor's degree or higher, percent of persons age 25+, 2009-2013" = "YlOrBr",
                               "Veterans, 2009-2013" = "YlOrBr",
                               "Mean travel time to work (minutes), workers age 16+, 2009-2013" = "YlGnBu",
                               "Housing units, 2014" = "YlGnBu",
                               "Homeownership rate, 2009-2013" = "YlOrBr",
                               "Housing units in multi-unit structures, percent, 2009-2013" = "YlOrBr",
                               "Median value of owner-occupied housing units, 2009-2013" = "YlGnBu",
                               "Households, 2009-2013" = "YlOrBr",
                               "Persons per household, 2009-2013" = "YlGnBu",
                               "Per capita money income in past 12 months (2013 dollars), 2009-2013" = "YlGnBu",
                               "Median household income, 2009-2013" = "YlGnBu",
                               "Persons below poverty level, percent, 2009-2013" = "YlOrBr",
                               "Private nonfarm establishments, 2013" = "Greens",
                               "Private nonfarm employment,  2013" = "Greens",
                               "Private nonfarm employment, percent change, 2012-2013" = "Greens",
                               "Nonemployer establishments, 2013" = "Greens",
                               "Total number of firms, 2007" = "Greens",
                               "Black-owned firms, percent, 2007" = "Greens",
                               "American Indian- and Alaska Native-owned firms, percent, 2007" = "Greens",
                               "Asian-owned firms, percent, 2007" = "Greens",
                               "Native Hawaiian- and Other Pacific Islander-owned firms, percent, 2007" = "Greens",
                               "Hispanic-owned firms, percent, 2007" = "Greens",
                               "Women-owned firms, percent, 2007" = "Greens",
                               "Manufacturers shipments, 2007 ($1,000)" = "YlGnBu",
                               "Merchant wholesaler sales, 2007 ($1,000)" = "YlGnBu",
                               "Retail sales, 2007 ($1,000)" = "YlGnBu",
                               "Retail sales per capita, 2007" = "YlGnBu",
                               "Accommodation and food services sales, 2007 ($1,000)" = "YlGnBu",
                               "Building permits, 2014" = "Greens",
                               "Land area in square miles, 2010" = "Greens",
                               "Population per square mile, 2010" = "Greens")
    
    # How should the bins be calculated for the map?
    reactive$binSel = switch(input$var1,
                             "Trump County score" = 6,
                             "Trump 2016 Share" = 6,
                             "Clinton 2016 Share" = 6,
                             "Population, 2014 estimate" = 8,
                             "Population, 2010 (April 1) estimates base" = 8,
                             "Population, percent change - April 1, 2010 to July 1, 2014" = 6,
                             "Population, 2010" = 8,
                             "Persons under 5 years, percent, 2014" = 5,
                             "Persons under 18 years, percent, 2014" = 6,
                             "Persons 65 years and over, percent, 2014" = 6,
                             "Female persons, percent, 2014" = 6,
                             "White alone, percent, 2014" = 6,
                             "Black or African American alone, percent, 2014" = 6,
                             "American Indian and Alaska Native alone, percent, 2014" = 6,
                             "Asian alone, percent, 2014" = 6,
                             "Native Hawaiian and Other Pacific Islander alone, percent, 2014" = 5,
                             "Two or More Races, percent, 2014" = 6,
                             "Hispanic or Latino, percent, 2014" = 6,
                             "White alone, not Hispanic or Latino, percent, 2014" = 6,
                             "Living in same house 1 year & over, percent, 2009-2013" = 6,
                             "Foreign born persons, percent, 2009-2013" = 6,
                             "Language other than English spoken at home, pct age 5+, 2009-2013" = 6,
                             "High school graduate or higher, percent of persons age 25+, 2009-2013" = 6,
                             "Bachelor's degree or higher, percent of persons age 25+, 2009-2013" = 6,
                             "Veterans, 2009-2013" = 6,
                             "Mean travel time to work (minutes), workers age 16+, 2009-2013" = 6,
                             "Housing units, 2014" = 6,
                             "Homeownership rate, 2009-2013" = 6,
                             "Housing units in multi-unit structures, percent, 2009-2013" = 6,
                             "Median value of owner-occupied housing units, 2009-2013" = 6,
                             "Households, 2009-2013" = 5,                             
                             "Persons per household, 2009-2013" = 5,
                             "Per capita money income in past 12 months (2013 dollars), 2009-2013" = 6,
                             "Median household income, 2009-2013" = 6,
                             "Persons below poverty level, percent, 2009-2013" = 6,
                             "Private nonfarm establishments, 2013" = 6,
                             "Private nonfarm employment,  2013" = 6,
                             "Private nonfarm employment, percent change, 2012-2013" = 6,
                             "Nonemployer establishments, 2013" = 6,
                             "Total number of firms, 2007" = 6,
                             "Black-owned firms, percent, 2007" = 5,
                             "American Indian- and Alaska Native-owned firms, percent, 2007" = 5,
                             "Asian-owned firms, percent, 2007" = 5,
                             "Native Hawaiian- and Other Pacific Islander-owned firms, percent, 2007" = 3,
                             "Hispanic-owned firms, percent, 2007" = 5,
                             "Women-owned firms, percent, 2007" = 6,
                             "Manufacturers shipments, 2007 ($1,000)" = 6,
                             "Merchant wholesaler sales, 2007 ($1,000)" = 6,
                             "Retail sales, 2007 ($1,000)" = 6,
                             "Retail sales per capita, 2007" = 6,
                             "Accommodation and food services sales, 2007 ($1,000)" = 5,
                             "Building permits, 2014" = 5,
                             "Land area in square miles, 2010" = 5,
                             "Population per square mile, 2010" = 6)
    
    # How many digits (past 0) should numbers of each category appear with?
    reactive$digitSel = switch(input$var1,
                               "Trump County score" = 2,
                               "Trump 2016 Share" = 2,
                               "Clinton 2016 Share" = 2,
                               "Population, 2014 estimate" = 0,
                               "Population, 2010 (April 1) estimates base" = 0,
                               "Population, percent change - April 1, 2010 to July 1, 2014" = 2,
                               "Population, 2010" = 0,
                               "Persons under 5 years, percent, 2014" = 2,
                               "Persons under 18 years, percent, 2014" = 2,
                               "Persons 65 years and over, percent, 2014" = 2,
                               "Female persons, percent, 2014" = 2,
                               "White alone, percent, 2014" = 2,
                               "Black or African American alone, percent, 2014" = 2,
                               "American Indian and Alaska Native alone, percent, 2014" = 2,
                               "Asian alone, percent, 2014" = 2,
                               "Native Hawaiian and Other Pacific Islander alone, percent, 2014" = 2,
                               "Two or More Races, percent, 2014" = 2,
                               "Hispanic or Latino, percent, 2014" = 2,
                               "White alone, not Hispanic or Latino, percent, 2014" = 2,
                               "Living in same house 1 year & over, percent, 2009-2013" = 2,
                               "Foreign born persons, percent, 2009-2013" = 2,
                               "Language other than English spoken at home, pct age 5+, 2009-2013" = 2,
                               "High school graduate or higher, percent of persons age 25+, 2009-2013" = 2,
                               "Bachelor's degree or higher, percent of persons age 25+, 2009-2013" = 2,
                               "Veterans, 2009-2013" = 0,
                               "Mean travel time to work (minutes), workers age 16+, 2009-2013" = 2,
                               "Housing units, 2014" = 0,
                               "Homeownership rate, 2009-2013" = 2,
                               "Housing units in multi-unit structures, percent, 2009-2013" = 2,
                               "Median value of owner-occupied housing units, 2009-2013" = 0,
                               "Households, 2009-2013" = 0,
                               "Persons per household, 2009-2013" = 2,
                               "Per capita money income in past 12 months (2013 dollars), 2009-2013" = 0,
                               "Median household income, 2009-2013" = 0,
                               "Persons below poverty level, percent, 2009-2013" = 2,
                               "Private nonfarm establishments, 2013" = 0,
                               "Private nonfarm employment,  2013" = 0,
                               "Private nonfarm employment, percent change, 2012-2013" = 2,
                               "Nonemployer establishments, 2013" = 0,
                               "Total number of firms, 2007" = 0,
                               "Black-owned firms, percent, 2007" = 2,
                               "American Indian- and Alaska Native-owned firms, percent, 2007" = 2,
                               "Asian-owned firms, percent, 2007" = 2,
                               "Native Hawaiian- and Other Pacific Islander-owned firms, percent, 2007" = 2,
                               "Hispanic-owned firms, percent, 2007" = 2,
                               "Women-owned firms, percent, 2007" = 2,
                               "Manufacturers shipments, 2007 ($1,000)" = 0,
                               "Merchant wholesaler sales, 2007 ($1,000)" = 0,
                               "Retail sales, 2007 ($1,000)" = 0,
                               "Retail sales per capita, 2007" = 0,
                               "Accommodation and food services sales, 2007 ($1,000)" = 0,
                               "Building permits, 2014" = 0,
                               "Land area in square miles, 2010" = 0,
                               "Population per square mile, 2010" = 0)
    
    reactive$percentSel = switch(input$var1,
                                 "Trump County score" = 0,
                                 "Trump 2016 Share" = 1,
                                 "Clinton 2016 Share" = 1,
                                 "Population, 2014 estimate" = 0,
                                 "Population, 2010 (April 1) estimates base" = 0,
                                 "Population, percent change - April 1, 2010 to July 1, 2014" = 1,
                                 "Population, 2010" = 0,
                                 "Persons under 5 years, percent, 2014" = 1,
                                 "Persons under 18 years, percent, 2014" = 1,
                                 "Persons 65 years and over, percent, 2014" = 1,
                                 "Female persons, percent, 2014" = 1,
                                 "White alone, percent, 2014" = 1,
                                 "Black or African American alone, percent, 2014" = 1,
                                 "American Indian and Alaska Native alone, percent, 2014" = 1,
                                 "Asian alone, percent, 2014" = 1,
                                 "Native Hawaiian and Other Pacific Islander alone, percent, 2014" = 1,
                                 "Two or More Races, percent, 2014" = 1,
                                 "Hispanic or Latino, percent, 2014" = 1,
                                 "White alone, not Hispanic or Latino, percent, 2014" = 1,
                                 "Living in same house 1 year & over, percent, 2009-2013" = 1,
                                 "Foreign born persons, percent, 2009-2013" = 1,
                                 "Language other than English spoken at home, pct age 5+, 2009-2013" = 1,
                                 "High school graduate or higher, percent of persons age 25+, 2009-2013" = 1,
                                 "Bachelor's degree or higher, percent of persons age 25+, 2009-2013" = 1,
                                 "Veterans, 2009-2013" = 0,
                                 "Mean travel time to work (minutes), workers age 16+, 2009-2013" = 0,
                                 "Housing units, 2014" = 0,
                                 "Homeownership rate, 2009-2013" = 1,
                                 "Housing units in multi-unit structures, percent, 2009-2013" = 1,
                                 "Median value of owner-occupied housing units, 2009-2013" = 2,
                                 "Households, 2009-2013" = 0,
                                 "Persons per household, 2009-2013" = 0,
                                 "Per capita money income in past 12 months (2013 dollars), 2009-2013" = 2,
                                 "Median household income, 2009-2013" = 2,
                                 "Persons below poverty level, percent, 2009-2013" = 1,
                                 "Private nonfarm establishments, 2013" = 0,
                                 "Private nonfarm employment,  2013" = 0,
                                 "Private nonfarm employment, percent change, 2012-2013" = 1,
                                 "Nonemployer establishments, 2013" = 0,
                                 "Total number of firms, 2007" = 0,
                                 "Black-owned firms, percent, 2007" = 1,
                                 "American Indian- and Alaska Native-owned firms, percent, 2007" = 1,
                                 "Asian-owned firms, percent, 2007" = 1,
                                 "Native Hawaiian- and Other Pacific Islander-owned firms, percent, 2007" = 1,
                                 "Hispanic-owned firms, percent, 2007" = 1,
                                 "Women-owned firms, percent, 2007" = 1,
                                 "Manufacturers shipments, 2007 ($1,000)" = 2,
                                 "Merchant wholesaler sales, 2007 ($1,000)" = 2,
                                 "Retail sales, 2007 ($1,000)" = 2,
                                 "Retail sales per capita, 2007" = 2,
                                 "Accommodation and food services sales, 2007 ($1,000)" = 2,
                                 "Building permits, 2014" = 0,
                                 "Land area in square miles, 2010" = 0,
                                 "Population per square mile, 2010" = 0)
    
  })
  
  # Initialize reactive click event data
  click <- reactiveValues(clickedCounty = "NULL")
  
  # Observe the event that the user clicks on a polygon
  observeEvent(input$map1_shape_click, {
    click$clickedCounty = input$map1_shape_click$id
    click_data=click$clickedCounty
    
    # Reactively recreate datatable seen in sidebar of app
    output$selectedFactor <- renderDataTable({
      data <- data.frame(merged2@data[,"CountyState"], reactive$dataSel, stringsAsFactors = F)
      colnames(data) <- c("CountyState", paste0(input$var1))
      if(click$clickedCounty != "NULL"){
        data <- data[data$CountyState==click_data,]
      }
      # Round data to show so that it's friendly on the eyes
      if(reactive$percentSel == 1){
        data[,2] <- paste0(round(data[,2], 0),"%")
      } else if(reactive$percentSel == 2){
        data[,2] <- paste0("$",format(round(data[,2],2), big.mark = ",", trim=TRUE))
      }
      else {
        data[,2] <- format(round(data[,2],2), big.mark = ",", trim=TRUE)
      }
      # Create output type-compatible datatable 
      if(input$screen_height > 900){
        dt <- emc_datatable(data)
      } else {
        dt <- emc_datatable(data,5)
      }
      dt
    })
    
    data <- merged2@data
  })
  
  # Observe the event that the user clicks on a part of the map that isn't a polygon. This means that the user has
  # clicked off of the polygon that they had selected before, which means we should 
  # 'reset the click data'
  observeEvent(input$map1_click, {
    click$clickedCounty <- "NULL"
  })
  
  # Initialize datatable seen in sidebar of app
  output$selectedFactor <- renderDataTable({
    data <- data.frame(merged2@data[,"CountyState"], reactive$dataSel, stringsAsFactors = F)
    colnames(data) <- c("CountyState", paste0(input$var1))
    # Summarize the factor chosen by the user based on County id
    # If the data is a proportion, round it to two decimal places, else, keep it as an integer

    if(reactive$percentSel == 1){
      data[,2] <- paste0(round(data[,2], 0),"%")
    } else if(reactive$percentSel == 2){
      data[,2] <- paste0("$",format(round(data[,2],2), big.mark = ",", trim=TRUE))
    }
    else {
      data[,2] <- format(round(data[,2],2), big.mark = ",", trim=TRUE)
    }
    
    # Create output type-compatible datatable 
    if(input$screen_height > 900){
      dt <- emc_datatable(data)
    } else {
      dt <- emc_datatable(data,5)
    }
    dt
  })
  
  data <- merged2@data
  
  
  
  output$map1 <- renderLeaflet({
    # Convert the labels to HTML
    labels <- sprintf(
      with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>', WhoWon, '<br>',"Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',"Trump Counties Score: ",round(TrumpCountiesScore, digits=2)))
    ) %>% lapply(htmltools::HTML)
    
    # Define bins for mapping.  Bins are a numeric vector that defines the boundaries between intervals.
    breaks_qt <- signif(getJenksBreaks(merged2@data$TrumpCountiesScore, k = 6), 3)
    # Specify color information.. what color scheme and what values should be used to calculate the color scheme break points?
    pal = colorBin("RdPu", domain = merged2@data$TrumpCountiesScore, bins = breaks_qt)
    
    m = leaflet() %>% addProviderTiles("OpenStreetMap.Mapnik") %>%
      setView(lat = 40.7, lng = -79.8, zoom = 4) %>%
      emc_polygons(merged2@data$TrumpCountiesScore ,pal,labels) %>%
      addLegend(pal = pal, values = merged2@data$TrumpCountiesScore, opacity = 0.7, title = "Trump Counties Score:", position = "bottomright", layerId = 1)
  })
  
  # In this implentation, it will look nicer if the leaflet map is not completely regenerated every time a different
  # factor is chosen. With a call to leafletProxy(), changes to the map can be made reactively (all we have to do
  # is clear the previous shapes and legend)
  observeEvent(input$var1, {
    
    # Convert the labels to HTML
    labels <- sprintf(
      reactive$textSel
    ) %>% lapply(htmltools::HTML)
    
    # Specify color information.. what color scheme and what values should be used to calculate the color scheme break points?
    breaks_qt <- round(getJenksBreaks(reactive$dataSel, k = reactive$binSel), digits = reactive$digitSel)
    # Define bins for mapping.  Bins are a numeric vector that defines the boundaries between intervals.
    if (mean(reactive$dataSel) > 1){
      breaks_qt <- unique(getJenksBreaks(reactive$dataSel, k = reactive$binSel))
      breaks_qt[1] <- min(reactive$dataSel)
      breaks_qt[reactive$binSel] <- max(reactive$dataSel)
    }
    else {
      breaks_qt <- round(getJenksBreaks(reactive$dataSel, k = reactive$binSel), digits = reactive$digitSel)
      breaks_qt[1] <- round(min(reactive$dataSel)-.01, digits=reactive$digitSel)
      breaks_qt[reactive$binSel] <- round(max(reactive$dataSel)+.01, digits=reactive$digitSel)
    }

    pal = colorBin(reactive$colorSel, domain = reactive$dataSel, bins = breaks_qt)
    
    leafletProxy("map1", data = merged2) %>% 
      clearShapes() %>%
      clearGroup("polygons") %>%
      removeControl(1) %>%
      emc_polygons(reactive$dataSel, pal, labels) %>%
      addLegend(pal = pal, values = reactive$dataSel, opacity = 0.7, title = reactive$titleSel, position = "bottomright",
                # Displaying proportions as percentages in our context looks prettier. You can change the way that proportions
                # (or any other type of data) are displayed using labFormat. labFormat takes implicit arguments
                # type, cuts, and p which can be used in this case to display proportion ranges as percentage ranges.
                labFormat = function(type, cuts, p){
                  n = length(cuts)
                  if(reactive$percentSel == 1) {
                    paste0(round(cuts[-n],0), "%", " &ndash; ", round(cuts[-1],0), "%")
                  }
                  else if(reactive$percentSel == 2){
                    paste0("$",format(round(cuts[-n],2), big.mark = ",", trim=TRUE), " &ndash; ", "$",format(round(cuts[-1],2), big.mark = ",", trim=TRUE))}
                  else {
                    paste0(format(mround(cuts[-n],1), big.mark = ",", trim=TRUE), " &ndash; ", format(mround(cuts[-1],1), big.mark = ",", trim=TRUE))
                  }
                },
                layerId = 1)
  })
  
  observeEvent(input$go, {
    if(input$d1 == ""){
      showNotification("Please select a first differential.", type = "error")
    } else if(input$d2 == ""){
      showNotification("Please select a second differential.", type = "error")
    } else {
      
      reactiveDiffSel1 = switch(input$d1,
                                "Trump 2016 Share" = merged2@data$TrumpShare, 
                                "Clinton 2016 Share" = merged2@data$ClintonShare)
      reactiveDiffSel2 = switch(input$d2,
                                "Trump 2016 Share" = merged2@data$TrumpShare, 
                                "Clinton 2016 Share" = merged2@data$ClintonShare)
      
      dif <- reactiveDiffSel1 - reactiveDiffSel2
      
      reactive$textSel <- with(merged2@data, paste("<strong>",CountyState,"<strong>",'<br>',
                                                   WhoWon, '<br>',
                                                   "Population (2014 estimate):", format(PST045214, big.mark = ",", trim=TRUE),'<br>',
                                                   "Trump Counties Score: ",round(TrumpCountiesScore, digits=2), '<br>',
                                                   input$d1, ": ", paste0(round(reactiveDiffSel1, digits=0),"%%"), '<br>',
                                                   input$d2, ": ", paste0(round(reactiveDiffSel2, digits=0),"%%"), '<br>',
                                                   input$d1," - ", input$d2,": ", paste0(round(dif, digits=0),"%%")))
      # Convert the labels to HTML
      labels <- sprintf(
        reactive$textSel
      ) %>% lapply(htmltools::HTML)
      #Get differential jenks breaks
      breaks_qt <- round(getJenksBreaks(dif, k = 6), digits = 2)
      
      #Determine color scale for differential based on number of breaks above zero
      color_pal = switch(as.character(length(breaks_qt[breaks_qt>0])),
                         "0" = c("#a50f14", "#de2d26", "#fb6a4a", "#fc9272", "#fcbba1", "#fee5d9"),
                         "1" = c("#67001f", "#b2182b", "#d6604d", "#f4a582", "#fddbc7", "#92c5de"),
                         "2" = c("#b2182b", "#d6604d", "#f4a582", "#fddbc7", "#d1e5f0", "#4393c3"),
                         "3" = c("#b2182b", "#ef8a62", "#fddbc7", "#d1e5f0", "#67a9cf", "#2166ac"),
                         "4" = c("#d6604d", "#fddbc7", "#d1e5f0", "#92c5de", "#4393c3", "#2166ac"),
                         "5" = c("#f4a582", "#d1e5f0", "#92c5de", "#4393c3", "#2166ac", "#053061"),
                         "6" = c("#eff3ff", "#c6dbef", "#9ecae1", "#6baed6", "#3182bd", "#08519c"))
      #Deal with case where number of breaks is not within 0-6 range
      if(!(length(breaks_qt[breaks_qt > 0]) %in% c(0,6))){
        breaks_qt <- sort(c(breaks_qt, 0))
      } else {
        breaks_qt <- round(getJenksBreaks(dif, k = 7), digits = 2)
      }
      
      for(z in 6:7){
        if(max(dif) > breaks_qt[z]) {
          breaks_qt[z] <- round(max(breaks_qt[z]+.01), digits = 2)
        }
        if(min(dif) < breaks_qt[1]) {
          breaks_qt[1] <- round(min(breaks_qt[1]-.01), digits = 2)
        }
      }
      
      pal = c()
      for(i in 1:length(dif)){
        for(j in 1:(length(breaks_qt)-1)){
          if(is.na(dif[i])){
            pal[i] = NA
            break
          } 
          else if(dif[i] >= breaks_qt[j] & dif[i] < breaks_qt[j+1]){
            pal[i] = color_pal[2*j/2]
            break
          }
        }
      }
      
      labs = c()
      for(k in 1:(length(breaks_qt)-1)){
        labs[k] = paste0(round(breaks_qt[k], digits = 0), "%", " &ndash; ", round(breaks_qt[k+1], digits = 0), "%")
      }
      #pal = colorBin("RdBu", domain = dif, bins = breaks_qt)
      
      
      
      leafletProxy("map1", data = dif) %>% 
        clearShapes() %>%
        clearGroup("polygons") %>%
        removeControl(1) %>%
        emc_polygons(dif, pal, labels, func = F) %>%
        addLegend(colors = color_pal, labels = labs, opacity = 0.7, title = paste0(input$d1," &ndash; ", input$d2), position = "bottomright",
                  layerId = 1)
    }
  })
  
  })
# Run the application in a browser
shinyApp(ui = ui, server = server)
